---
title: "`r paste('chronplot for' , group)`"
date: "`r paste('Compiled on', format(Sys.time(), '%d %B, %Y'))`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, echo=FALSE, message=FALSE}
library(lubridate)
library(RColorBrewer)
library(ggplot2)
library(ggiraph)

# choose a named RColorBrewer pallet (multiple colors), or a single color (name
# or hex); see brewer.pal.info for list and display.brewer.all() to view all
# pallets
pal <- "Paired"

# evidence codes to lump -- uncomment/edit as needed
# this is a list of named vectors where the vector name is used to place all
# codes in the corresponding vector (e.g. 'S = c("S", "S7", "M")' replaces all
# "S", "S7", and "M" with "S"). Note that any code that is not already in
# variable "codelevels" in function "chronplot" (below) will need to be added
# there.
# lump <- list(S = c("S", "S7", "M"), O = c("", "F", "O", "NC"))

# evidence codes to remove -- uncomment/edit as needed
# this is a vector of evidence codes that will be not be plotted
# no_plot_codes <- c("PE", "UN")


# load data ----

# ebird data -- data are provided to this template by the calling R script
# ebird <- read.delim("March2022dataset.txt", quote = "", as.is = TRUE)
# ebird <- read.csv("Vireonidae.csv", as.is = TRUE)


# data prep ----

# flag the pigeon entries so they are not removed with the rest of the domestics
ebird <- transform(ebird, category = ifelse(common_name == "Rock Pigeon", "pigeon", category))

# remove domestic, spuh, and slash taxonomic categories (optional)
taxa <- c("species", "issf", "hybrid", "form", "pigeon")
ebird <- ebird[ebird$category %in% taxa, ]

# remove not valid (reason = exotic) records
ebird <- subset(ebird, approved != "0")

# order by TAXONOMIC.ORDER
ebird <- ebird[order(ebird$taxonomic_order), ]

# put all dates within the same year -- ignores leap year
ebird$observation_date <- sub("^20\\d\\d", "2016", ebird$observation_date)

# remove white space from evidence codes
ebird$breeding_code <- trimws(ebird$breeding_code)

# lump evidence codes if lump has been set
if (exists("lump")) {
  for (i in seq_along(lump)) {
    indx <- ebird$breeding_code %in% lump[[i]]
    ebird[indx, "breeding_code"] <- names(lump)[i]
  }
}

# remove unneeded evidence codes
if (exists("no_plot_codes")) {
  ebird <- ebird[! ebird$breeding_code %in% no_plot_codes, ]
}

# Add new columns for URL
ebird$front <- 'https://ebird.org/checklist/'
ebird$ChecklistLink <- with(ebird, paste0(front, sampling_event_identifier))

# chron plot function ----

chronplot <- function(comname, ebird, pal, cex.x.axis = 0.9, cex.y.axis = 0.8) {
  # comname is the common name of the species to plot, ebird is the WBBA data
  # downloaded from ebird function assumes that column names have not been
  # changed from ebird download
  

# make a date label that doesn't have 2016 in it
# making a second date column as to not screw with other code
ebird$datelabel <-ebird$observation_date 

# make datelabel a date object
ebird$datelabel2 <- as.Date(ebird$datelabel, "%Y-%m-%d")

# remove year from this label
ebird$datelabelshort <-format(ebird$datelabel2, format="%m-%d")


  # rename columns because ebird names are long
  ### NEW: Keep GLOBAL.UNIQUE.IDENTIFIER as guid
  cols <- c("common_name", "breeding_code", "observation_date", "global_unique_identifier", "ChecklistLink", "datelabelshort")
  newnames <- c("name", "code", "obsdate", "guid", "link", "datelabelshort")
  ebird <- ebird[ebird$common_name == comname, cols]
  names(ebird) <- newnames

  # make obsdate a date object
  ebird$obsdate <- as.Date(ebird$obsdate, "%Y-%m-%d")

  # set order that box plots will be plotted.
  # http://stackoverflow.com/questions/19681586/ordering-bars-in-barplot
  # this will be the order that codes are plotted in.
  # this vector will need updating if any new codes are introduced via "lump".
  codelevels <- c("H", "S", "S7", "M", "T", "P", "C", "B", "CN", "NB", "A", "N",
                  "DD", "ON", "NE", "FS", "CF", "NY", "FY", "FL", "PE", "UN",
                  "F", "", "O", "NC")

  if (! all(ebird$code %in% codelevels)) {
    warn <- paste("Not all eBird codes (breeding_code) for",
                  comname, "are in codelevels")
    warning(warn)
  }

  # associate colors with codelevels
  if (pal %in% rownames(brewer.pal.info)) {
    n <- brewer.pal.info[pal, "maxcolors"]
    codecolors <- colorRampPalette(brewer.pal(n, pal))(length(codelevels))
  } else {
    codecolors <- rep(pal, length(codelevels))
  }

  names(codecolors) <- codelevels

  # used droplevels so that codes that where not observed are not plotted;
  # remove droplevels if you'd like unobserved codes to be included on the plot
  ebird$code <- droplevels(factor(ebird$code, levels = codelevels,
                                  ordered = TRUE))

  # plot "empty" box plot
  # boxplot(obsdate ~ code, horizontal = TRUE, cex.axis = cex.y.axis, xaxt = "n",
  #         data = ebird, border = "white", main = comname, las = 2,
  #         xlab = "Date", ylab = "Breeding Codes", show.names = TRUE)

  date0 <- round_date(min(ebird$obsdate), "month")
  date1 <- round_date(max(ebird$obsdate), "month")
  labels <- seq(from = date0, to = date1, by = "month")

  if (length(unique(month(ebird$obsdate))) == 1) {
    labels <- c(min(ebird$obsdate), max(ebird$obsdate))
    labels <- unique(labels)  # in case there's only one obs
  } else {
    # limit labels to those within observed range
    int <- interval(min(ebird$obsdate), max(ebird$obsdate))
    labels <- labels[labels %within% int]

    if (nrow(ebird) > 1 && length(labels) == 1) {
      labels <- unique(c(min(ebird$obsdate), max(ebird$obsdate)))
    }
  }

  # use format "%m/%d" for e.g. 06/01
  # use format "%b %d" for e.g. "Aug 23"
  names(labels) <- format(labels, "%b %d")

  ### NEW: add col column
  ebird$col <- codecolors[ebird$code]


  # ggiraph code for boxplot and interactive points
  gg_point = ggplot(data = ebird) +
    geom_boxplot(aes(x = obsdate, y = code)) +
    geom_point_interactive(aes(x = obsdate, y = code, color = col, tooltip = datelabelshort, data_id = datelabelshort,
                              onclick=paste0('window.open("', link , '", "_blank")')),
      show.legend = FALSE, position = position_jitter(width = .2, height = .2)) +
    theme_minimal()  + labs(title = comname)
  
  girafe(ggobj = gg_point, width_svg=10, options = list(opts_sizing(rescale = TRUE)))
  
}


# plot species ----

# print a chronology plot for each species to a single html; note that this can
# be time consuming if plotting many species
sp <- unique(ebird$common_name)

# print a chronplot for each species in sp
htmltools::tagList(
  lapply(sp, function(i) chronplot(i, ebird, pal))
)
```
